#!/usr/bin/env python3

import os, sys, stat

from sysfile import CFind


class CFindDir(CFind):
	def __init__(self, path=None):
		CFind.__init__(self, path)

	def handle_file(self, path):
		if os.path.isdir(path):
			os.chmod(path, stat.S_IRWXU|stat.S_IRGRP|stat.S_IXGRP)
			
def main():
	find = CFindDir()

	l = len(sys.argv)
	if l <= 1:
		return find.walk()

	for i in range(1, l):

#	cur = os.path.abspath(sys.argv[i])
		setattr(find, "_path", sys.argv[i])
		find.walk()

if __name__ =="__main__":
	main()
