#!/usr/bin/env bash


top -bn1 | awk '
BEGIN{
	cpu=0
	mem_total=0
	mem_used=0
	mem_buffers=0
	mem_cached=0
}
/Cpu|Mem/{
	if ($0 ~ "Cpu") {
		cpu=$2 + $4 + $(NF-1)
		next
	}

	if ($0 ~ "buffers") {
		mem_total = $3
		mem_used = $5
		mem_buffers = $(NF-1)
		next
	}

	if ($0 ~ "cached") {
		mem_cached = $(NF -2)
		exit
	}
}
END {
	mem_used=(mem_used - mem_buffers - mem_cached)
	printf("CPU %.1f%%|MEM %0.2f%%(%0.2fM/%0.2fM)\n", cpu,
			mem_used * 100 / mem_total,
			mem_used / 1024,
			mem_total / 1024)
}'

